# Generated by Django 3.2.3 on 2021-06-16 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_instausers_dateofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instausers',
            name='dateofbirth',
        ),
    ]
