# Generated by Django 3.2.3 on 2021-06-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_auto_20210621_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='imgFeed',
            field=models.FileField(upload_to='upload'),
        ),
    ]
